[FEATS] Add body property to custom which tags are clickable
concordnow/ember-table pull request #5
Opened 2019-11-19 16:57 UTC by frykten

Faut que je crée une issue chez eux :
Ils ont harcodé que certaines balises sont clickables (et donc pas sélectionnables). Rien de blocker mais c'est dommage de pas pouvoir faire de maj click.

2019-11-19 17:35 UTC, david-ratier commented on addon/components/ember-tr/component.js
> +    let possibleParentElementTags = isParentElementTagsString  ? clickableParentElementTags : 'input, button, label, a, select';
double espace

2019-11-20 15:48 UTC, ctjhoa requested changes
test missing

2019-11-25 17:17 UTC, frykten commented
Si vous voyez rien de flagrant, je leur envoie ça direct

2019-11-25 17:22 UTC, ghost approved these changes

2019-12-05 17:18 UTC, ctjhoa approved these changes

2021-10-19 07:48 UTC, closed without merging